### PR TITLE
Update star_wars_the_bad_batch_2.yaml

### PR DESCRIPTION
**Pull request by Qbsoon**
Premiere date changed. 16 episodes (two on the first week)

### CODE REVIEW

**Comment by SirIndubitable** [comment]
I probably wont approve this review because this show is automatically imported from The Movie DB.
https://www.themoviedb.org/tv/105971-star-wars-the-bad-batch/season/2?language=en-US

So if this gets submitted, within a day it would get reverted by the automated scripts.

I'll look into how hard it is to add episodes on TMDB, if it's too difficult, I'll try to rethink how this is done so that we can make corrections like this.

**Comment by Qbsoon** [comment]
Why TMDB? Have you thought of IMDB api?
It is more common and as it seems - more accurate.

**Comment by SirIndubitable** [comment]
Yeah I looked into IMDB first, but it doesn't have a free API where TMDB does.

**Comment by SirIndubitable** [comment]
It looks like The TVDB has info already, so probably is updated first.  I'll look into how hard it would be to pull the info from there.

**Comment by SirIndubitable** [comment]
Sadly it looks like TheTVDB doesn't have a free API either.  I went ahead and updated the episodes on TMDB, so I'll go ahead and accept this, and it shouldn't get overwritten

**Review by SirIndubitable — APPROVED** [review]

**Pull request merged**
